# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['search_gui_pyside.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('blue_style.qss', '.'),
        ('green_style.qss', '.'),
        ('purple_style.qss', '.'),
        ('checkmark.png', '.'),
        ('checkmark_blue.png', '.'),
        ('checkmark_green.png', '.'),
        ('checkmark_purple.png', '.'),
        ('down_arrow.png', '.'),
        ('down_arrow_blue.png', '.'),
        ('down_arrow_green.png', '.'),
        ('down_arrow_purple.png', '.'),
        ('radio_checked_blue.png', '.'),
        ('radio_checked_green.png', '.'),
        ('radio_checked_purple.png', '.')
    ],
    hiddenimports=[
        'jieba',
        'PIL', 
        'pytesseract', 
        'pdf2image', 
        'packaging', 
        'requests',
        'PySide6.QtNetwork',
        'PySide6.QtGui',
        'PySide6.QtCore',
        'PySide6.QtWidgets',
        'pandas', 
        'openpyxl', 
        'pptx',
        'docx', 
        'markdown',
        'bs4', 
        'striprtf',
        'email',
        'chardet',
        'extract_msg',
        'whoosh',
        'csv'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='文智搜',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='文智搜',
)
